// Code generated by protoc-gen-go.
// source: rello.proto
// DO NOT EDIT!

/*
Package rello is a generated protocol buffer package.

It is generated from these files:
	rello.proto

It has these top-level messages:
	ChecklistUpdate
	Model
	CheckItem
	Action
	Data
	CheckList
	Card
	Board
	MemberCreator
*/
package rello

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChecklistUpdate struct {
	Model  *Model  `protobuf:"bytes,1,opt,name=model" json:"model,omitempty"`
	Action *Action `protobuf:"bytes,2,opt,name=action" json:"action,omitempty"`
}

func (m *ChecklistUpdate) Reset()                    { *m = ChecklistUpdate{} }
func (m *ChecklistUpdate) String() string            { return proto.CompactTextString(m) }
func (*ChecklistUpdate) ProtoMessage()               {}
func (*ChecklistUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChecklistUpdate) GetModel() *Model {
	if m != nil {
		return m.Model
	}
	return nil
}

func (m *ChecklistUpdate) GetAction() *Action {
	if m != nil {
		return m.Action
	}
	return nil
}

type Model struct {
	Id         string       `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name       string       `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	IdBoard    string       `protobuf:"bytes,3,opt,name=idBoard" json:"idBoard,omitempty"`
	IdCard     string       `protobuf:"bytes,4,opt,name=idCard" json:"idCard,omitempty"`
	Pos        int32        `protobuf:"varint,5,opt,name=pos" json:"pos,omitempty"`
	CheckItems []*CheckItem `protobuf:"bytes,6,rep,name=checkItems" json:"checkItems,omitempty"`
}

func (m *Model) Reset()                    { *m = Model{} }
func (m *Model) String() string            { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()               {}
func (*Model) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Model) GetCheckItems() []*CheckItem {
	if m != nil {
		return m.CheckItems
	}
	return nil
}

type CheckItem struct {
	State       string `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
	IdChecklist string `protobuf:"bytes,2,opt,name=idChecklist" json:"idChecklist,omitempty"`
	Id          string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Pos         int32  `protobuf:"varint,6,opt,name=pos" json:"pos,omitempty"`
	RelloId     int64  `protobuf:"varint,7,opt,name=relloId" json:"relloId,omitempty"`
	UserId      string `protobuf:"bytes,8,opt,name=userId" json:"userId,omitempty"`
}

func (m *CheckItem) Reset()                    { *m = CheckItem{} }
func (m *CheckItem) String() string            { return proto.CompactTextString(m) }
func (*CheckItem) ProtoMessage()               {}
func (*CheckItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Action struct {
	Id              string         `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	IdMemberCreator string         `protobuf:"bytes,2,opt,name=idMemberCreator" json:"idMemberCreator,omitempty"`
	Data            *Data          `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	Type            string         `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	Date            string         `protobuf:"bytes,5,opt,name=date" json:"date,omitempty"`
	MemberCreator   *MemberCreator `protobuf:"bytes,6,opt,name=memberCreator" json:"memberCreator,omitempty"`
}

func (m *Action) Reset()                    { *m = Action{} }
func (m *Action) String() string            { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()               {}
func (*Action) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Action) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Action) GetMemberCreator() *MemberCreator {
	if m != nil {
		return m.MemberCreator
	}
	return nil
}

type Data struct {
	CheckItem *CheckItem `protobuf:"bytes,1,opt,name=checkItem" json:"checkItem,omitempty"`
	Checklist *CheckList `protobuf:"bytes,2,opt,name=checklist" json:"checklist,omitempty"`
	Card      *Card      `protobuf:"bytes,3,opt,name=card" json:"card,omitempty"`
	Board     *Board     `protobuf:"bytes,4,opt,name=board" json:"board,omitempty"`
}

func (m *Data) Reset()                    { *m = Data{} }
func (m *Data) String() string            { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()               {}
func (*Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Data) GetCheckItem() *CheckItem {
	if m != nil {
		return m.CheckItem
	}
	return nil
}

func (m *Data) GetChecklist() *CheckList {
	if m != nil {
		return m.Checklist
	}
	return nil
}

func (m *Data) GetCard() *Card {
	if m != nil {
		return m.Card
	}
	return nil
}

func (m *Data) GetBoard() *Board {
	if m != nil {
		return m.Board
	}
	return nil
}

type CheckList struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *CheckList) Reset()                    { *m = CheckList{} }
func (m *CheckList) String() string            { return proto.CompactTextString(m) }
func (*CheckList) ProtoMessage()               {}
func (*CheckList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Card struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id        string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	ShortLink string `protobuf:"bytes,3,opt,name=shortLink" json:"shortLink,omitempty"`
	IdShort   int32  `protobuf:"varint,4,opt,name=idShort" json:"idShort,omitempty"`
}

func (m *Card) Reset()                    { *m = Card{} }
func (m *Card) String() string            { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()               {}
func (*Card) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type Board struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id        string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	ShortLink string `protobuf:"bytes,3,opt,name=shortLink" json:"shortLink,omitempty"`
}

func (m *Board) Reset()                    { *m = Board{} }
func (m *Board) String() string            { return proto.CompactTextString(m) }
func (*Board) ProtoMessage()               {}
func (*Board) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type MemberCreator struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	AvatarHas string `protobuf:"bytes,2,opt,name=avatarHas" json:"avatarHas,omitempty"`
	FullName  string `protobuf:"bytes,3,opt,name=fullName" json:"fullName,omitempty"`
	Initials  string `protobuf:"bytes,4,opt,name=initials" json:"initials,omitempty"`
	Username  string `protobuf:"bytes,5,opt,name=username" json:"username,omitempty"`
}

func (m *MemberCreator) Reset()                    { *m = MemberCreator{} }
func (m *MemberCreator) String() string            { return proto.CompactTextString(m) }
func (*MemberCreator) ProtoMessage()               {}
func (*MemberCreator) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto.RegisterType((*ChecklistUpdate)(nil), "rello.ChecklistUpdate")
	proto.RegisterType((*Model)(nil), "rello.Model")
	proto.RegisterType((*CheckItem)(nil), "rello.CheckItem")
	proto.RegisterType((*Action)(nil), "rello.Action")
	proto.RegisterType((*Data)(nil), "rello.Data")
	proto.RegisterType((*CheckList)(nil), "rello.CheckList")
	proto.RegisterType((*Card)(nil), "rello.Card")
	proto.RegisterType((*Board)(nil), "rello.Board")
	proto.RegisterType((*MemberCreator)(nil), "rello.MemberCreator")
}

func init() { proto.RegisterFile("rello.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 528 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x54, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x55, 0xda, 0x24, 0xdd, 0x4c, 0x28, 0xbb, 0xb2, 0x56, 0x28, 0x42, 0x2b, 0x51, 0x45, 0x42,
	0xca, 0xa9, 0xa0, 0x72, 0xe3, 0x06, 0xe5, 0x40, 0xa5, 0x5d, 0x0e, 0x46, 0xdc, 0xb8, 0xb8, 0xb5,
	0xd1, 0x5a, 0x9b, 0xd4, 0x55, 0xe2, 0x45, 0xe2, 0x33, 0xf8, 0x04, 0xce, 0x7c, 0x08, 0xbf, 0x85,
	0x66, 0xec, 0x38, 0x69, 0x7b, 0x41, 0xe2, 0xe6, 0x37, 0x6f, 0x3c, 0x7e, 0x33, 0xf3, 0x12, 0xc8,
	0x5b, 0x55, 0xd7, 0x66, 0x79, 0x68, 0x8d, 0x35, 0x2c, 0x21, 0x50, 0x7e, 0x85, 0xcb, 0xf5, 0xbd,
	0xda, 0x3d, 0xd4, 0xba, 0xb3, 0x5f, 0x0e, 0x52, 0x58, 0xc5, 0x4a, 0x48, 0x1a, 0x23, 0x55, 0x5d,
	0x44, 0x8b, 0xa8, 0xca, 0x57, 0x4f, 0x96, 0xee, 0xda, 0x1d, 0xc6, 0xb8, 0xa3, 0xd8, 0x4b, 0x48,
	0xc5, 0xce, 0x6a, 0xb3, 0x2f, 0x26, 0x94, 0x34, 0xf7, 0x49, 0xef, 0x28, 0xc8, 0x3d, 0x59, 0xfe,
	0x8a, 0x20, 0xa1, 0x7b, 0xec, 0x29, 0x4c, 0xb4, 0xa4, 0x8a, 0x19, 0x9f, 0x68, 0xc9, 0x18, 0xc4,
	0x7b, 0xd1, 0x28, 0xba, 0x9e, 0x71, 0x3a, 0xb3, 0x02, 0x66, 0x5a, 0xbe, 0x37, 0xa2, 0x95, 0xc5,
	0x94, 0xc2, 0x3d, 0x64, 0xcf, 0x20, 0xd5, 0x72, 0x8d, 0x44, 0x4c, 0x84, 0x47, 0xec, 0x0a, 0xa6,
	0x07, 0xd3, 0x15, 0xc9, 0x22, 0xaa, 0x12, 0x8e, 0x47, 0xf6, 0x1a, 0x60, 0x87, 0xfd, 0x6c, 0xac,
	0x6a, 0xba, 0x22, 0x5d, 0x4c, 0xab, 0x7c, 0x75, 0xe5, 0xc5, 0xad, 0x7b, 0x82, 0x8f, 0x72, 0xca,
	0xdf, 0x11, 0x64, 0x81, 0x61, 0xd7, 0x90, 0x74, 0x56, 0x58, 0xe5, 0xa5, 0x3a, 0xc0, 0x16, 0x90,
	0x6b, 0x19, 0xe6, 0xe4, 0x45, 0x8f, 0x43, 0xbe, 0xbf, 0xe9, 0x59, 0x7f, 0xf1, 0xa8, 0x3f, 0xaf,
	0x36, 0x1d, 0xd4, 0x16, 0x30, 0x23, 0x69, 0x1b, 0x59, 0xcc, 0x16, 0x51, 0x35, 0xe5, 0x3d, 0xc4,
	0x8e, 0x1f, 0x3b, 0xd5, 0x6e, 0x64, 0x71, 0xe1, 0x3a, 0x76, 0xa8, 0xfc, 0x13, 0x41, 0xea, 0x86,
	0x7c, 0x36, 0xd2, 0x0a, 0x2e, 0xb5, 0xbc, 0x53, 0xcd, 0x56, 0xb5, 0xeb, 0x56, 0x09, 0x6b, 0x5a,
	0x2f, 0xf4, 0x34, 0xcc, 0x5e, 0x40, 0x2c, 0x85, 0x15, 0x24, 0x37, 0x5f, 0xe5, 0x7e, 0x3c, 0x1f,
	0x84, 0x15, 0x9c, 0x08, 0x54, 0x6f, 0x7f, 0x1c, 0x82, 0x7a, 0x3c, 0x63, 0x0c, 0xed, 0x41, 0xc3,
	0xce, 0x28, 0x4f, 0xb1, 0xb7, 0x30, 0x6f, 0x8e, 0x1e, 0x4c, 0xa9, 0xe2, 0x75, 0x6f, 0x99, 0x31,
	0xc7, 0x8f, 0x53, 0x71, 0xee, 0x31, 0x3e, 0xc9, 0x96, 0x90, 0x85, 0x75, 0x78, 0xcf, 0x9d, 0x6f,
	0x6c, 0x48, 0x09, 0xf9, 0x61, 0x15, 0x27, 0xf9, 0xb7, 0xba, 0xb3, 0x7c, 0x48, 0xc1, 0x6e, 0x77,
	0xbd, 0xa7, 0x86, 0x6e, 0xd1, 0x3f, 0x9c, 0x08, 0x34, 0xfc, 0xd6, 0xf4, 0xe6, 0x1a, 0x0c, 0x4f,
	0xd6, 0xe3, 0x8e, 0x2a, 0x5f, 0x79, 0x93, 0x60, 0xf1, 0xb0, 0xdc, 0x68, 0xb4, 0x5c, 0xb7, 0x8d,
	0x49, 0xbf, 0x8d, 0x72, 0x0b, 0x31, 0x59, 0xf4, 0x1f, 0x72, 0xd9, 0x0d, 0x64, 0xdd, 0xbd, 0x69,
	0xed, 0xad, 0xde, 0x3f, 0x78, 0x0f, 0x0d, 0x01, 0xf7, 0x59, 0x7c, 0x46, 0x48, 0x02, 0x13, 0xde,
	0xc3, 0x72, 0x03, 0x89, 0xfb, 0x3e, 0xfe, 0xfb, 0x91, 0xf2, 0x67, 0x04, 0xf3, 0x63, 0x93, 0x9c,
	0xda, 0xeb, 0x06, 0x32, 0xf1, 0x5d, 0x58, 0xd1, 0x7e, 0x14, 0x9d, 0x2f, 0x3b, 0x04, 0xd8, 0x73,
	0xb8, 0xf8, 0xf6, 0x58, 0xd7, 0x9f, 0x50, 0x85, 0x2b, 0x1e, 0x30, 0x72, 0x7a, 0xaf, 0xad, 0x16,
	0x75, 0xe7, 0x1d, 0x15, 0x30, 0x72, 0xe8, 0x6c, 0x52, 0xef, 0x9c, 0x15, 0xf0, 0x36, 0xa5, 0x3f,
	0xd5, 0x9b, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xac, 0x60, 0x17, 0x4b, 0xb8, 0x04, 0x00, 0x00,
}
