// Code generated by protoc-gen-go.
// source: rello.proto
// DO NOT EDIT!

/*
Package rello is a generated protocol buffer package.

It is generated from these files:
	rello.proto

It has these top-level messages:
	Empty
	ChecklistUpdate
	Model
	CheckItem
	Action
	Data
	CheckList
	Card
	Board
	MemberCreator
*/
package rello

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/adamryman/ambition-model/ambition-service/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ChecklistUpdate struct {
	Model  *Model  `protobuf:"bytes,1,opt,name=model" json:"model,omitempty"`
	Action *Action `protobuf:"bytes,2,opt,name=action" json:"action,omitempty"`
}

func (m *ChecklistUpdate) Reset()                    { *m = ChecklistUpdate{} }
func (m *ChecklistUpdate) String() string            { return proto.CompactTextString(m) }
func (*ChecklistUpdate) ProtoMessage()               {}
func (*ChecklistUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ChecklistUpdate) GetModel() *Model {
	if m != nil {
		return m.Model
	}
	return nil
}

func (m *ChecklistUpdate) GetAction() *Action {
	if m != nil {
		return m.Action
	}
	return nil
}

type Model struct {
	Id         string       `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name       string       `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	IdBoard    string       `protobuf:"bytes,3,opt,name=idBoard" json:"idBoard,omitempty"`
	IdCard     string       `protobuf:"bytes,4,opt,name=idCard" json:"idCard,omitempty"`
	Pos        int32        `protobuf:"varint,5,opt,name=pos" json:"pos,omitempty"`
	CheckItems []*CheckItem `protobuf:"bytes,6,rep,name=checkItems" json:"checkItems,omitempty"`
}

func (m *Model) Reset()                    { *m = Model{} }
func (m *Model) String() string            { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()               {}
func (*Model) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Model) GetCheckItems() []*CheckItem {
	if m != nil {
		return m.CheckItems
	}
	return nil
}

type CheckItem struct {
	State       string `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
	IdChecklist string `protobuf:"bytes,2,opt,name=idChecklist" json:"idChecklist,omitempty"`
	Id          string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Pos         int32  `protobuf:"varint,6,opt,name=pos" json:"pos,omitempty"`
}

func (m *CheckItem) Reset()                    { *m = CheckItem{} }
func (m *CheckItem) String() string            { return proto.CompactTextString(m) }
func (*CheckItem) ProtoMessage()               {}
func (*CheckItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Action struct {
	Id              string         `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	IdMemberCreator string         `protobuf:"bytes,2,opt,name=idMemberCreator" json:"idMemberCreator,omitempty"`
	Data            *Data          `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	Type            string         `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	Date            string         `protobuf:"bytes,5,opt,name=date" json:"date,omitempty"`
	MemberCreator   *MemberCreator `protobuf:"bytes,6,opt,name=memberCreator" json:"memberCreator,omitempty"`
}

func (m *Action) Reset()                    { *m = Action{} }
func (m *Action) String() string            { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()               {}
func (*Action) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Action) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Action) GetMemberCreator() *MemberCreator {
	if m != nil {
		return m.MemberCreator
	}
	return nil
}

type Data struct {
	CheckItem *CheckItem `protobuf:"bytes,1,opt,name=checkItem" json:"checkItem,omitempty"`
	Checklist *CheckList `protobuf:"bytes,2,opt,name=checklist" json:"checklist,omitempty"`
	Card      *Card      `protobuf:"bytes,3,opt,name=card" json:"card,omitempty"`
	Board     *Board     `protobuf:"bytes,4,opt,name=board" json:"board,omitempty"`
}

func (m *Data) Reset()                    { *m = Data{} }
func (m *Data) String() string            { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()               {}
func (*Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Data) GetCheckItem() *CheckItem {
	if m != nil {
		return m.CheckItem
	}
	return nil
}

func (m *Data) GetChecklist() *CheckList {
	if m != nil {
		return m.Checklist
	}
	return nil
}

func (m *Data) GetCard() *Card {
	if m != nil {
		return m.Card
	}
	return nil
}

func (m *Data) GetBoard() *Board {
	if m != nil {
		return m.Board
	}
	return nil
}

type CheckList struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *CheckList) Reset()                    { *m = CheckList{} }
func (m *CheckList) String() string            { return proto.CompactTextString(m) }
func (*CheckList) ProtoMessage()               {}
func (*CheckList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type Card struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id        string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	ShortLink string `protobuf:"bytes,3,opt,name=shortLink" json:"shortLink,omitempty"`
	IdShort   int32  `protobuf:"varint,4,opt,name=idShort" json:"idShort,omitempty"`
}

func (m *Card) Reset()                    { *m = Card{} }
func (m *Card) String() string            { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()               {}
func (*Card) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type Board struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id        string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	ShortLink string `protobuf:"bytes,3,opt,name=shortLink" json:"shortLink,omitempty"`
}

func (m *Board) Reset()                    { *m = Board{} }
func (m *Board) String() string            { return proto.CompactTextString(m) }
func (*Board) ProtoMessage()               {}
func (*Board) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type MemberCreator struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	AvatarHas string `protobuf:"bytes,2,opt,name=avatarHas" json:"avatarHas,omitempty"`
	FullName  string `protobuf:"bytes,3,opt,name=fullName" json:"fullName,omitempty"`
	Initials  string `protobuf:"bytes,4,opt,name=initials" json:"initials,omitempty"`
	Username  string `protobuf:"bytes,5,opt,name=username" json:"username,omitempty"`
}

func (m *MemberCreator) Reset()                    { *m = MemberCreator{} }
func (m *MemberCreator) String() string            { return proto.CompactTextString(m) }
func (*MemberCreator) ProtoMessage()               {}
func (*MemberCreator) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func init() {
	proto.RegisterType((*Empty)(nil), "rello.Empty")
	proto.RegisterType((*ChecklistUpdate)(nil), "rello.ChecklistUpdate")
	proto.RegisterType((*Model)(nil), "rello.Model")
	proto.RegisterType((*CheckItem)(nil), "rello.CheckItem")
	proto.RegisterType((*Action)(nil), "rello.Action")
	proto.RegisterType((*Data)(nil), "rello.Data")
	proto.RegisterType((*CheckList)(nil), "rello.CheckList")
	proto.RegisterType((*Card)(nil), "rello.Card")
	proto.RegisterType((*Board)(nil), "rello.Board")
	proto.RegisterType((*MemberCreator)(nil), "rello.MemberCreator")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Rello service

type RelloClient interface {
	CheckListWebhook(ctx context.Context, in *ChecklistUpdate, opts ...grpc.CallOption) (*Empty, error)
}

type relloClient struct {
	cc *grpc.ClientConn
}

func NewRelloClient(cc *grpc.ClientConn) RelloClient {
	return &relloClient{cc}
}

func (c *relloClient) CheckListWebhook(ctx context.Context, in *ChecklistUpdate, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/rello.Rello/CheckListWebhook", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Rello service

type RelloServer interface {
	CheckListWebhook(context.Context, *ChecklistUpdate) (*Empty, error)
}

func RegisterRelloServer(s *grpc.Server, srv RelloServer) {
	s.RegisterService(&_Rello_serviceDesc, srv)
}

func _Rello_CheckListWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChecklistUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelloServer).CheckListWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rello.Rello/CheckListWebhook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelloServer).CheckListWebhook(ctx, req.(*ChecklistUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rello.Rello",
	HandlerType: (*RelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckListWebhook",
			Handler:    _Rello_CheckListWebhook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("rello.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 579 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x54, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0x26, 0x6d, 0x92, 0x35, 0x27, 0xbb, 0x6e, 0x19, 0x96, 0x25, 0x94, 0x82, 0x65, 0x40, 0x28,
	0x5e, 0xb4, 0x52, 0xef, 0xf6, 0x4e, 0xab, 0xe2, 0xc2, 0xae, 0xc2, 0x88, 0x78, 0xe3, 0xcd, 0xa4,
	0x19, 0xb7, 0x43, 0x93, 0x4c, 0x48, 0x66, 0x85, 0xde, 0xfa, 0x06, 0xe2, 0x13, 0x78, 0xed, 0x83,
	0xf8, 0x00, 0xbe, 0x82, 0x0f, 0x22, 0xf3, 0x93, 0x49, 0xda, 0xde, 0x08, 0xde, 0xe5, 0x9c, 0xef,
	0xcb, 0xf9, 0xfb, 0x3e, 0x06, 0xe2, 0x9a, 0xe5, 0xb9, 0x98, 0x57, 0xb5, 0x90, 0x02, 0x05, 0x3a,
	0x18, 0x4f, 0xee, 0x84, 0xb8, 0xcb, 0xd9, 0x82, 0x56, 0x7c, 0x41, 0xcb, 0x52, 0x48, 0x2a, 0xb9,
	0x28, 0x1b, 0x43, 0xc2, 0x27, 0x10, 0xbc, 0x2a, 0x2a, 0xb9, 0xc3, 0x9f, 0xe0, 0x7c, 0xb5, 0x61,
	0xeb, 0x6d, 0xce, 0x1b, 0xf9, 0xa1, 0xca, 0xa8, 0x64, 0x08, 0x43, 0x50, 0x88, 0x8c, 0xe5, 0x89,
	0x37, 0xf5, 0x66, 0xf1, 0xf2, 0x74, 0x6e, 0xaa, 0xdf, 0xaa, 0x1c, 0x31, 0x10, 0x7a, 0x0c, 0x21,
	0x5d, 0xab, 0x82, 0xc9, 0x40, 0x93, 0xce, 0x2c, 0xe9, 0xb9, 0x4e, 0x12, 0x0b, 0xe2, 0x1f, 0x1e,
	0x04, 0xfa, 0x3f, 0xf4, 0x10, 0x06, 0x3c, 0xd3, 0x15, 0x23, 0x32, 0xe0, 0x19, 0x42, 0xe0, 0x97,
	0xb4, 0x60, 0xfa, 0xf7, 0x88, 0xe8, 0x6f, 0x94, 0xc0, 0x09, 0xcf, 0x5e, 0x08, 0x5a, 0x67, 0xc9,
	0x50, 0xa7, 0xdb, 0x10, 0x5d, 0x42, 0xc8, 0xb3, 0x95, 0x02, 0x7c, 0x0d, 0xd8, 0x08, 0x8d, 0x60,
	0x58, 0x89, 0x26, 0x09, 0xa6, 0xde, 0x2c, 0x20, 0xea, 0x13, 0x3d, 0x05, 0x58, 0xab, 0x7d, 0xae,
	0x25, 0x2b, 0x9a, 0x24, 0x9c, 0x0e, 0x67, 0xf1, 0x72, 0x64, 0x87, 0x5b, 0xb5, 0x00, 0xe9, 0x71,
	0xf0, 0x0e, 0x22, 0x07, 0xa0, 0x0b, 0x08, 0x1a, 0x49, 0x25, 0xb3, 0x93, 0x9a, 0x00, 0x4d, 0x21,
	0xe6, 0x99, 0x3b, 0x93, 0x9d, 0xb9, 0x9f, 0xb2, 0xeb, 0x0d, 0x8f, 0xd6, 0xf3, 0x7b, 0xeb, 0xd9,
	0x61, 0x43, 0x37, 0x2c, 0xfe, 0xe5, 0x41, 0x68, 0x2e, 0x76, 0x74, 0x9f, 0x19, 0x9c, 0xf3, 0xec,
	0x96, 0x15, 0x29, 0xab, 0x57, 0x35, 0xa3, 0x52, 0xd4, 0xb6, 0xed, 0x61, 0x1a, 0x3d, 0x02, 0x3f,
	0xa3, 0x92, 0xea, 0xe6, 0xf1, 0x32, 0xb6, 0xbb, 0xbe, 0xa4, 0x92, 0x12, 0x0d, 0xa8, 0x59, 0xe4,
	0xae, 0x72, 0xb3, 0xa8, 0x6f, 0x95, 0x53, 0x5a, 0xeb, 0xcb, 0x45, 0x9a, 0xc7, 0xd0, 0x15, 0x9c,
	0x15, 0x7b, 0x0d, 0x43, 0x5d, 0xf1, 0xa2, 0xd5, 0xbf, 0x8f, 0x91, 0x7d, 0x2a, 0xfe, 0xe9, 0x81,
	0xaf, 0x5a, 0xa2, 0x39, 0x44, 0xee, 0xb6, 0xd6, 0x40, 0xc7, 0xe7, 0xef, 0x28, 0x8e, 0xef, 0x0e,
	0x7b, 0xc0, 0xbf, 0xe1, 0x8d, 0x24, 0x1d, 0x45, 0x6d, 0xbb, 0x6e, 0x0d, 0xd2, 0x6d, 0xab, 0xcc,
	0x40, 0x34, 0xa0, 0xdc, 0x9b, 0x8a, 0xd6, 0x29, 0x9d, 0x7b, 0xb5, 0x8f, 0x88, 0x81, 0xf0, 0xc2,
	0x4a, 0xae, 0x8a, 0x3b, 0xa9, 0xbc, 0x9e, 0x54, 0x46, 0x8d, 0x41, 0xab, 0x06, 0x4e, 0xc1, 0xd7,
	0x7e, 0xfb, 0x07, 0x2e, 0x9a, 0x40, 0xd4, 0x6c, 0x44, 0x2d, 0x6f, 0x78, 0xb9, 0xb5, 0x8e, 0xe8,
	0x12, 0xc6, 0xe3, 0xef, 0x55, 0xa8, 0x07, 0x0c, 0x48, 0x1b, 0xe2, 0x6b, 0x08, 0x8c, 0xd9, 0xff,
	0xbb, 0x09, 0xfe, 0xe6, 0xc1, 0xd9, 0xbe, 0x49, 0x0e, 0xed, 0x35, 0x81, 0x88, 0x7e, 0xa1, 0x92,
	0xd6, 0x6f, 0x68, 0x63, 0xcb, 0x76, 0x09, 0x34, 0x86, 0x07, 0x9f, 0xef, 0xf3, 0xfc, 0xad, 0x9a,
	0xc2, 0x14, 0x77, 0xb1, 0xc2, 0x78, 0xc9, 0x25, 0xa7, 0x79, 0x63, 0x1d, 0xe5, 0x62, 0x85, 0xdd,
	0x37, 0xac, 0xd6, 0xd3, 0x1b, 0x67, 0xb9, 0x78, 0xf9, 0x0e, 0x02, 0xa2, 0x94, 0x40, 0xaf, 0x61,
	0xe4, 0x8e, 0xff, 0x91, 0xa5, 0x1b, 0x21, 0xb6, 0xe8, 0xb2, 0x2f, 0x79, 0xf7, 0x14, 0x8d, 0x5b,
	0xf5, 0xcc, 0x5b, 0x75, 0xfa, 0xf5, 0xf7, 0x9f, 0xef, 0x83, 0x10, 0x7b, 0x8b, 0x2b, 0xef, 0x49,
	0x1a, 0xea, 0x97, 0xec, 0xd9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x14, 0x24, 0xf2, 0xff, 0xfd,
	0x04, 0x00, 0x00,
}
