CREATE TABLE checks(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	checkItemId INTEGER NOT NULL,
	datetime DATE NOT NULL
);

CREATE TABLE checkItems(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	trelloId TEXT NOT NULL,
	userId INTEGER NOT NULL
);

